name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Build
        run: nr build --base /MachineLearningLectures/

      - name: Deploy to LyxWxj.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: LyxWxj/LyxWxj.github.io
          publish_branch: main
          publish_dir: ./dist
          destination_dir: MachineLearningLectures
          keep_files: true
